kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: data-apps-traefik-role-binding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: data-apps-traefik-role
subjects:
  - kind: ServiceAccount
    name: data-apps-traefik-account
    namespace: data-apps